version: '3.7'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/volume:/data/db

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb

volumes:
  mongodb_data_container:
