name: Build Go Image
on:
  workflow_run:
    # only if the app build and test successfully
    workflows: ['Run Tests']
    branches: [main]
    types:
      - completed
jobs:
  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./backend/Dockerfile.production
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/casino:latest
      # - name: Run the image in a container
      #   uses: addnab/docker-run-action@v3
      #   with:
      #     image: ${{ secrets.DOCKERHUB_USERNAME }}/casino:latest
      #     run: |
      #       echo "runing the docker image"
      #       echo "Testing the go app endpoints"
      #       echo ${{ steps.docker_build.outputs.digest }}
