name: frontend pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./frontend/casino-ip2

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with: 
        node-version: 16
    
    - name: install node dependencies
      run: npm install
    
    - name: run tests
      run:  npm run test -- --coverage --update-snapshot --watchAll=false

    - name: coverage
      uses: codecov/codecov-action@v2
      with:
        directory: ./frontend/casino-ip2/coverage
        token: ${{ secrets.CODECOV_TOKEN }}
        file: clover.xml
        flags: unittests # optional
        name: codecov-umbrella # optional

    - name: build app
      run: CI='' npm run build
