name: frontend pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: frontend/casino-ip2

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
      with: 
        node-version: 18.x
    
    - name: install node dependencies
      run: npm install 
      
    - name: build app
      run: npm run build
    
    # - name: run test
    #   run: npm run test -- --watchAll=false --coverage

  test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./frontend/casino-ip2
    
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: test coverage
      uses: artiomtr/jest-coverage-report-action@v2
      with:
        skip-step: install
        working-directory: ./frontend/casino-ip2
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-script: npm run test -- --watchAll=false --coverage --testLocationInResults --json --outputFile="report.json"
        threshold: 75

  #TODO
  #deploy:
