name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbsetup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database
    steps:
    - uses: actions/setup-go@v3
    - run: docker-compose up -d
    
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
  #      os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test ./...
      
