
name: Go

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
      #  os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    
    - name: Setup Mongo DB in Docker
      run: docker-compose up -d
      working-directory: ./database
      
    - name: Run Tests
      run: |
        sudo go test ./... -coverprofile coverage.out -covermode count
        sudo go tool cover -func coverage.out
