
name: Go

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
      #  os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: docker-compose up -d
      working-directory: ./database
 #   - run: echo $(pwd)
#      working-directory: ./database
    - run: |
          go test ./... -coverprofile cover.out
          go tool cover -func cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}'
